### ISSUE TITLE
[Worrying] metadata.json contains nothing.

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#10]
Hi, just noticed that `bigdl search` stopped working, seems the issue is that this commit "https://github.com/Azathothas/Toolpacks/commit/9435050a617172201ee572539bcddb88e7b48707" overwrote the metadata.json with an empty file...

**Comment by xplshn** [comment]
It seems the metadata.json in Metis' repo is also periodically overwritten with an empty file.

**Comment by Azathothas** [comment]
As stated in https://github.com/Azathothas/Toolpacks/issues/7 , Hysp Metadata is a secondary source, and will be deprecated in the future.
As for the main, https://bin.ajam.dev/METADATA.json , the reason you are seeing periodic unexpected changes is due to [Cloudflare's Caching](https://developers.cloudflare.com/cache/)

wget has a flag for this : [wget --no-cache](https://www.gnu.org/software/wget/manual/html_node/HTTP-Options.html#index-proxy-1)
curl : https://www.baeldung.com/linux/curl-without-cache

And whatever lib/module you are using, there will likely be similar options to configure it. Or you could use a [`?$RANDOM`](https://www.baeldung.com/linux/curl-without-cache) when you construct the url, which will ensure you aren't fetching stale/cached content

**Comment by xplshn** [comment]
I meant, not that one, the one with descriptions, it is actively refreshed however, it is periodically overwritten with garbage

**Comment by xplshn** [comment]
I have modified the affected parts of my code, but this doesn't help, it only adds 24 lines of code that could be avoided if the metadata.json file wasn't periodically overwritten with garbage.

Doesn't seem like a problem of caching, since the file in your repo is also overwritten with an empty file sometimes, so, no matter what I do, can't get around it by myself

**Comment by xplshn** [comment]
it seems this is fixed? I don't know what fixed it. Closing for now.
