### ISSUE TITLE
[Q] Found lots of duplicated binaries, were they all duplicated on purpose?

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#15]
I know that some programs change their functionality based on the name of the binary, like the sudo and sudoedit, they check what "$0" is. But were this all meant to be like that? Some are misleading, like elinks-lite. Also, for elinks, I suggest providing a staticx option, because the packaged versions are all built with GPM (mouse support for TTYs and terminals)
```
]/Documents/TrulyMine/bigdl_fast @ jq '.packages | map(select(.architecture == "x86_64" and .sha != null)) | group_by(.sha) | map(select(length > 1)) | .[] | .[].name'
metadata.json
"ansi2txt"
"lsd"
"elinks-lite"
"elinks"
"u-root"
"uroot"
"sysinfo-collector"
"system-info-collector"
"sudo"
"sudoedit"
"gobusybox"
"u-root-busybox"
"uroot-busybox"
"wtf"
"wtfutil"
"nu"
"nushell"
"bat"
"batcat"
"jira-cli"
"jira"
"rg"
"ripgrep"
"gitpod-cli"
"gp"
"z"
"zoxide"
]/Documents/TrulyMine/bigdl_assembly @
```

**Comment by Azathothas** [comment]
Some binaries are duplicated deliberately due to the following reasons:
- `Symlinks`: Some pkgs install symlinks, which is sort of not possible when using static binaries, hence the duplication (`Example: nu nushell`)
- `aliases`: Similar to symlinks, some pkgs are referred by altnames (`Example: bat batcat`)
- `sane names`: some pkgs produce weird/inconsistently named binaries. I choose to keep the original name but also include a copy with a better one. (`Example: sysinfo-collector system-info-collector`)

**Comment by xplshn** [comment]
Okay! Great to know. I created a filter to filter these out of lists and search results, since it looks bad to have 2 times the same search results
