### ISSUE TITLE
No METADATA.json at https://bin.ajam.dev/arm64_v8a_Android/Baseutils/

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#20]

**Comment by Azathothas** [comment]
Currently testing. (It may be available but inaccurate at the time of you seeing)

Further, if I were to generate a tree, which format would you prefer (be easier to parse, for eg, just download this file and extract the dirnames directly)

```bash
# rclone tree --dirs-only --fast-list "r2:/bin/"
/
├── aarch64_arm64_Linux
│   └── Baseutils
├── arm64_v8a_Android
│   └── Baseutils
│       └── coreutils
├── x64_Windows
└── x86_64_Linux
    └── Baseutils
```
```bash
/
├── \aarch64_arm64_Linux
│   └── \aarch64_arm64_Linux\Baseutils
├── \arm64_v8a_Android
│   └── \arm64_v8a_Android\Baseutils
│       └── \arm64_v8a_Android\Baseutils\coreutils
├── \x64_Windows
└── \x86_64_Linux
    └── \x86_64_Linux\Baseutils
```

**Comment by Azathothas** [comment]
Once again I urge you to only use https://bin.ajam.dev/METADATA.json
This file remains immutable and is never overwritten in case any of the other json data are bad/empty/invalid.
Only when every other source is validated, the merged METADATA.json is created.
It's likely that you experienced https://github.com/Azathothas/Toolpacks/issues/10 because you keep relying on unreliable sources.
Also, I am planning to deprecate hysp's metadata entirely. 
No more description etc in the short term (you may still use it, it's just that I won't be fixing any bugs or maintaining hysp aymore) , but in the long term, I plan to add a better system which would be automatable and not rely on github's api for description etc.

I would still recommend the solution of creating a repo for bigdl `bigdl-registry`  and workout formats on your own as discussed in https://github.com/Azathothas/Toolpacks/issues/18#issuecomment-2109586322

**Comment by xplshn** [comment]
>I would still recommend the solution of creating a repo for bigdl bigdl-registry and workout formats on your own as discussed in https://github.com/Azathothas/Toolpacks/issues/18#issuecomment-2109586322

I don't understand Github Actions at all, if I knew how to make a GH action that runs every a few hours and adds the missing Description/Version/Updated field to `METADATA.json` that'd be great

**Comment by xplshn** [comment]
Now it works fine
