### ISSUE TITLE
Include Builds for rng tool

### ISSUE THREAD

**Issue by julio80221** [Azathothas/Toolpacks#26]
Rng tool armhf builf

**Comment by Azathothas** [comment]
Hello,
Due to some personal matters, I will be unable to fully address this issue for about a month or longer. 
In the meantime, I've updated the documentation with a new paragraph on supported architectures and OS at: https://github.com/Azathothas/Toolpacks/blob/main/Docs/README.md#supporting-more-architectures--os
> Note: 32-Bit Binaries will likely never be Supported/Added since that's now ancient and even embedded devices now ship with 64-Bit ARCH

Since `armhf` is 32 Bit based architecture, I have no plans to add it (Unless I have sufficient motivation/time in the sense someone donates a Build Server).

As for [`rng-tools`](https://github.com/nhorman/rng-tools), I will likely add it to the `x86_64` & `aarch64`  Targets.
I will also try to compile it for `armhf`, and if it builds successfully, I will add the build instruction & binary in a reply to this issue.
