### ISSUE TITLE
Request: bpftrace (& related tools)

### ISSUE THREAD

**Issue by Azathothas** [Azathothas/Toolpacks#30]
bpftrace: https://t.me/thcorg/25857/93770
https://t.me/thcorg/25857/93778

cc: @SkyperTHC

**Comment by Azathothas** [comment]
netexec blocker: https://github.com/JonathonReinhart/staticx/issues/288

**Comment by Azathothas** [comment]
Existing bpftrace doesn't work:
https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/aarch64_Linux/bins/bpftrace.sh
https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/x86_64_Linux/bins/bpftrace.sh

https://t.me/thcorg/25857/94219
![image](https://github.com/user-attachments/assets/8efafac7-e452-400a-8480-2e2739f031c5)


might have to ask @leleliu008 for yet another favour...

**Comment by leleliu008** [comment]
I will dig into it.

**Comment by leleliu008** [comment]
bpftrace is not supposed to be built as a fully statically linked executable.

Reference: https://github.com/bpftrace/bpftrace/issues/266

https://github.com/bpftrace/bpftrace/blob/master/.github/include/static.sh This shell script build a mostly statically linked executable rather than a fully statically linked executable.

Official provides AppImage format. That's the best choice.

**Comment by Azathothas** [comment]
I see.
Thanks for looking into it.
