### ISSUE TITLE
please update android-34 to android-35

### ISSUE THREAD

**Issue by leleliu008** [Azathothas/Toolpacks#38]
https://github.com/Azathothas/Toolpacks/blob/main/.github/runners/alpine-builder-ndk.sh#L51

I have changed Android NDK version from `r26d` to `r27c`, the MAX android api level is from `android-34` to `android-35`

**Comment by Azathothas** [comment]
Thanks again @leleliu008 
However, I think we will discontinue Android & Windows support because not enough demand and there already exists better centralized hub.

We will rather focus on Linux, & introduce *BSD
A somewhat related questions, have you considered creating a formula repository but for appimages?
The existing ones are all hackish and incomplete.
And this format let's us expand to GUI apps etc.
If you ever create a formula repository for appimages, it would be godsend.
Thank you.

**Comment by leleliu008** [comment]
> However, I think we will discontinue Android & Windows support because not enough demand and there already exists better centralized hub.

Well, I won't notice you if ndk-pkg has change.

> A somewhat related questions, have you considered creating a formula repository but for appimages?

Are you saying ppkg? Do you ask me if I would add a feature like export-appimage to ppkg? I myself do not use appimage, I like tarball files. I don't known the advantages of appimage. Does it can be used on all Linux platforms(e.g. glibc, uclibc, musl-libc, etc) and all linux distribution?

**Comment by Azathothas** [comment]
> Are you saying ppkg? Do you ask me if I would add a feature like export-appimage to ppkg?

Very different. I meant create a formula repo for GUI Apps. Using a format like AppImage or, better FlatImage: https://github.com/ruanformigoni/flatimage

>I don't known the advantages of appimage. Can it be used on all Linux platforms(e.g. glibc, uclibc, musl-libc, etc) and all linux distribution?

AppImage's portability depends on who made it & how.
But in most cases, or at least most AppImage published on GitHub, are not portable and will only work on glibc.
However, there are many well-made ones like: https://github.com/ivan-hc/Steam-appimage
https://github.com/Samueru-sama/GIMP-AppImage
https://github.com/Samueru-sama/OBS-Studio-AppImage
https://github.com/Samueru-sama/mpv-AppImage

These work on all Linux platforms because they also bundle the needed glibc.

**Comment by leleliu008** [comment]
> Very different. I meant create a formula repo for GUI Apps.

I don't think need a new formula repo to do so. This is a feature, we could extend ppkg to support it.

We could create a new foumula for GUI apps, most apps in https://github.com/leleliu008/ppkg-formula-repository-official-core/ are cli.

**Comment by leleliu008** [comment]
I am considering providing a option to pack all runtime (including libc) into the final tarball file if the package is not fully statically linked. That means a package do not rely on system's libc. totally self-contained.

**Comment by Azathothas** [comment]
It would be really helpful if you could join telegram...
Most discussion are happening at: https://t.me/official_loonix/63949
We have author of [FlatImage](https://github.com/ruanformigoni/flatimage) & [RunImage](https://github.com/VHSgunzo/runimage) there
Along with people from AM: https://github.com/ivan-hc/AM

>  This is a feature, we could extend ppkg to support it.

Would be better to discuss it there, if `ppkg` can build GUI Apps , I would add most apps

**Comment by leleliu008** [comment]
Sorry, I don't use any social media except github.com

ppkg is a package builder, you could build any package theoretically no matter cli or gui. If packages that you need is not available in  https://github.com/leleliu008/ppkg-formula-repository-official-core/ , you could ask me to add them.

**Comment by Azathothas** [comment]
https://docs.pkgforge.dev/orgs/pkgforge-core/projects/toolpacks-bincache/faq#android-deprecation
